#!/usr/bin/env python3
"""
Author : kyclark
Date   : 2019-04-19
Purpose: Check E6
"""

import re
import os
import sys
from Bio import AlignIO
from collections import Counter


# --------------------------------------------------
def check_e6(fasta):
    """Do good"""
    alignment = AlignIO.read(fasta, 'fasta')
    print(alignment)
    align_this(alignment)


# --------------------------------------------------
def align_this(data):
    dashes = {}
    for i, rec in enumerate(data):
        rec_id = rec['id']
        seq = rec['seq']
        #rec_id = rec.id
        #seq = str(rec.seq)
        print(i, rec_id, seq)
        match = re.search(r'^([-]+)', seq)
        num_dashes = 0
        if match:
            dash = match.group(1)
            num_dashes = len(dash)

        dashes[rec.id] = num_dashes

    print(dashes)
    nums = Counter(dashes.values())
    print(nums)
    print('max = {}'.format(max(nums)))

    if len(nums) == 2 and 0 in nums and nums[0] == 1:
        _ = nums.pop(0)
        not_zero = list(nums.keys())[0]
        print('There are just two uniq values, chop off {}'.format(not_zero))
        zero_seq = list(
            map(lambda kv: kv[0], filter(lambda kv: kv[1] == 0,
                                         dashes.items())))[0]
        print('Zero seq id = {}'.format(zero_seq))

    return 'Josh is great'


# --------------------------------------------------
def test_align():
    test1 = [{
        'id':
        'NC_023873',
        'seq':
        '------------ATGCCGCGACCGACTTCGGTGCAAGGT-TTGGCGAAGTCTCTGAACATCCCTTTAATTGATTTGCTCTTGGCCTGCAAATTTTGCTTAACATTTCTTACTAACATTGAAAAGCTTAAATTTGATGATGCCAATCTGCGGTTGCTATGGCGAGGGAGGCGTGTATATGGGTGTTGTCAATGCTGCTTAAGACTCTGCAGTAAAATAGAGCAAACCCTCTTCCCTCAAACATTTCTTTCTGCGCAAGCTTTCCATTAT---CTTGAAACTCATACTTCAAAAGTTC-CAGCAAGATGTGGTAGCTGTTACAGCCCTCTAACGCGTGAGGAGTATTTTAGTAGTGGAATTACCCGCAAGCTCCGGGTAGTAAGAGGAACGTTAAGAGGGGATTGTAACCTGTGTAAAAGTG------CAATATTAGAA------------TAA'
    }, {
        'id':
        'MG571090',
        'seq':
        '------------ATGGAGCGACCGTCTTCGGTTAAGGGTCTCTGCGCGTTAATACACTCTCCTCTT-ATTGATCTGCTTTTGCCCTGCAAGTTCTGCCATCGCTATCTAACAACATTGGAAAAACTGCGGTTTGATGCAGCTCCTTTTCAGCTAATCTGGAAAGAAGGGAACGTTTATGGGTGTTGTCAGACCTGCATCAGGCACTGCGGGCTTATTGAAAGGAACTATTTCCTCCAGGGAAAGATTGACGCCTTTTTGTTTGAGGAGAAGCTAGGTA-AGAAAGTAGAAGAGCTTACTCTGAGGTGCTCCTTTTGTTTGCATACTCTAACGTATTGGGAAAAAAAGGAGAATAAGTTTGATAGTGCATTGTTTCTAGTAAGAGGCAAGGTTCGAGGAACCTGTGATTTGTGTAGATTGCAGTATGCATGGGGAGAAGGCAACGCTTCGTGA'
    }, {
        'id':
        'NC_007150',
        'seq':
        '------------ATGGCTCGACCGACATCGGTGGAGGATCTTGGTAAACTTCTTGGGGTACCCTTC-ATTGACATTCTTCTTCCCTGCACCTTCTGCTCGCGCTTCCTTACTAACCTTGAAAAACTGCATTTCGACAAGAAGCCTCTGTCCTTGCTTTGGAAAGGAGGGTGTGTGTATGGGTGTTGTCAAAGTTGTGTGAGACGTTGCAGCTTTGTGGAAGCAGCCTTCCATCCACATAAAAGGGTCGCAGAGAAGGACT----------------TATATCAGTTGAGCAAGGACCCAGTAAGATGCTCTGCGTGTCAAGCAACTCTCAGCACGTCTGAGAAAGTCCGCTGTGCTGCAGAAGGCAGTTTGAGTCGTTGTAGAGGAAGGGTCAGGGGCCCCTGCGACCTTTGTCGCTTGC------CTTTGGAA---------------TAA'
    }, {
        'id':
        'unkown',
        'seq':
        'ATGGGGTACAGAATGGCTCGACCGACATCGGTAAAAGGTCTGGCGGCTCTAACAGGGGTTCCCCTT-GTTGATTTTCTTTTACCTTGCCACTTTTGCAAACGCTTCTTGACTAACATTGAAAAACTTAGGTTTGATGAATCGCCTCTGCGACTTCTTTGGAGAGAAGGGTGTGCTTTTGGGTGTTGCCTCGCATGCATAAGACTTTGCAGCAAAATAGAACGATCCTGCCATAAGAAAAAACATACCAACTGTAGAAAGATTAAAGAGAAGTTTGGTAAAGAAATTCTGGAAGTTG-GAATTAGGTGTAGTGCTTGCTACAAAAGGTTGCATTCTCGGGAAATACAAAAAAGTGCAAATAATCAAAGATTGTTTGAGGTCAGGGGAAAGGTCAGAGGATTTTGTGATCTTTGTTATTTGT------------GGACA------------TAA'
    }, {
        'id':
        'MF327538',
        'seq':
        '------------ATGGCTCGACCGACATCGGTAAAAGGTCTGGCGGCTCTAACAGGGGTTCCCCTT-GTTGATTTTCTTTTACCTTGCCACTTTTGCAAACGCTTCTTGACTAACATTGAAAAACTTAGGTTTGATGAATCGCCTCTGCGACTTCTTTGGAGAGAAGGGTGTGCTTTTGGGTGTTGCCTCGCATGCATAAGACTTTGCAGCAAAATAGAACGATCCTGCCATAAGAAAAAACATACCAACTGTAGAAAGATTAAAGAGAAGTTTGGTAAAGAAATTCTGGAAGTTG-GAATTAGGTGTAGTGCTTGCTACAAAAGGTTGCATTCTCGGGAAATACAAAAAAGTGCAAATAATCAAAGATTGTTTGAGGTCAGGGGAAAGGTCAGAGGATTTTGTGATCTTTGTTATTTGT------------GGACA------------TAA'
    }, {
        'id':
        'NC_013237',
        'seq':
        '------------ATGGCGCGACCGACAACGGTGAAAGGTCTCTCAGAGAGAACTGGAGCTTCATTT-ATTGACTTGCTTTTGCCTTGTAATTTTTGCTCACGCTTTCTTACTAACATAGAAAAAGCTTTTTTTGACTTATCACCTTTTCAACTTGTATGGAGGAATGACTGTGTGTATGGTTGCTGTCAAAAATGCATTAGAGATTGTGCATTGCTGGAAGAATCTTTTTATTTTGAAAAATTTTTATCTGAAAGTGAGCTTGAGGAG-------CTTTGGACGCGGTCAAAGGTGATTGTAAGGTGCCACCGGTGCATGAAAAGCCTTACAGAAATTGAAAAAAACTCTTGTAAATTTGAGAAGATTATAAGGTTGGTAAGAGGTCAGTATAGGGGACTTTGTGATTTGTGTCGCTTGT------CAGTTGAAGGA------------TGA'
    }, {
        'id':
        'DQ180494',
        'seq':
        '------------ATGGCGCGACCATCCACTGTCAAAGGTCTCTGCGCAGCTACCGGAGCTGCGTTT-TCTGATTTGCTGTTGCCTTGCACCTTTTGCCTGCGCTTTCTTACTGCTGTAGAAAAAGGTTTTTTTGATGCTTGCCCTTTGCAATTGCAGTGGAAAAAGAACTGTGCGTATGGGTGTTGCCTCAGCTGCCTGAGAAAGTGTGCCTTGCTTGAACATAACGTTTATTATGAAAGAAAACTTTCTGATTCTGAGCGAGTAGTT----TTGGGCCAGAGAGTCGATGAGTTTTCTGTGAGGTGTGGCTCTTGCATGAAACTGCTGGAAGCTTCGGAGAAACTTCGGTGCTGCAGTGAGAACAAATTGGACGTTGTGAGAGGAAGGGTTAGAGGAGTCTGTGGTCTTTGTCGACTAG------CAGTGGAAGCA------------TGA'
    }, {
        'id':
        'AY904724',
        'seq':
        '------------ATGGCGCGTCCATCAACGGTTAAAGGTCTCTGCGCAGCCACAGGGGCTGCATTT-TCTGATTTTCTGTTGCCTTGCACTTTTTGCCTGCGCTTTCTCACTTCTGTAGAAAAAGGCTTTTTCGATGCTTGCCCTTTGCAATTGCAGTGGAAGCGAAACTCAGCTTTTGGGTGCTGTCTCAGCTGCATAAGAAAGTGTGCATCGGTTGAACGCTCAGTGTTTTTTGAGAGAAAACTCACAGATGCAGAACTAGCAATT----TTATTACAGAAAAGAGACGAGTGTTTCATTAGGTGTGGCTATTGCATGAAGCAGCTGGAAGCCTCAGACAAACTTCGGTGCTGTCTTGCACAGGAATTGGACGTTGTCAGAGGCAGGGTTAGAGGAGTCTGTAGTCTTTGTCGCCTAT------CTGTAGAAGTA------------TGA'
    }, {
        'id':
        'NC_004765',
        'seq':
        '------------ATGGCGCGACCATCTTCAGTACAAGGTCTTTGCGCAGCCACCGGGGCTGCTTTT-GCTGACTTGCTTCTACCCTGCTCCTTTTGTTTGCGCTTTCTCACTTCTGTAGAGAAATCTCTTTTCGATGCTTACCCTTTGCAGTTGCAATGGAAACAGGGCTGTGCTTTTGGGTGCTGCCAGAGCTGCATACGAAAATGTGCTTTAGTTGAACGTGCATGCTATTTTCAGAGAAAAGTGACAGACTCTGAAGTTGCTGGT----TTGTTGGAGAGAGTAAGGGAGGCATGTGTTAGGTGTGGCTATTGCATGAGAGCTCTTGGACCTCCCGACAAAATCCAGTGCTGCCTCGAAAGAGACCTGGACCTTATCAGAGGAAAGGTTAGAGGACGCTGTGGTCTTTGTCGCCTTT------CGGTGGAAGGA------------TGA'
    }, {
        'id':
        'AY904722',
        'seq':
        '------------ATGGCGCGACCATCTTCTGTACAAGGTCTTTCCGCAGCCACCGGAGCTGCCTTT-ACCGATTTGCTTCTACCTTGCACCTTTTGCCTGCGCTTTCTCACCTCTGTAGAAAAAGCTCTCTTTGATGCTTACCCTTTGCAATTGCAGTGGAAATCTGGGTGTGCTTTTGCCTGCTGCCAGAGCTGCATAAGAAAATGCGCGCAGGTGGAAAGAAATTGCTATTTTGAGAGGCAAATGACTGAGACAGAGCTGGTGGGG----TTGTTATCCAGAGTGGAGGAGGCACTTATTAGGTGTGGCTATTGCATGAGAAGTCTTAAACCTGGTGATAAAGTTCGGTGCTGCGTTGAACACAAGCTGGACGTTATCAGAGGCCAGTGTAGAGGACTCTGTGGTTTGTGTCGCCTCT------CGTTGAAACCA------------TGA'
    }, {
        'id':
        'AY904723',
        'seq':
        '------------ATGGCGCGACCATCTTCTGTTCAAGGTCTTTGCGAAGCTACCGGGGCTAAATTT-TCAGATTTGCTTCTACCTTGCACGTTTTGCCTGCGCTTTCTCACCTCTGTAGAAAAAGCTCTTTTTGATGCTTTCCCTTTGCAACTGCGGTGGAAAGGGAGGTGTGCTTTTGGCTGCTGTCAAGGCTGCATAAGACTGTGTGCACAAATTGAGCGGCGTTTTTATTATGAGAGGAAAGTTACTGAGACAGAACTGTGCGGG----TTGCTAGACCATCCTGAGGCGGCATGTGTTAGGTGTGGCTTTTGCATGAGACGTCTCGGAACCTGTGACAAAGTTCGGTGCTGCTTTGAAAACGATCTGGACGTTGTGAGAGGCCAGGTTAGAGGACGCTGTGGTTTGTGTCGCCTAT------CTGTGGAAGTA------------TGA'
    }]
    assert align_this(test1) == 'Josh is great'


# --------------------------------------------------
def main():
    """Start here"""
    args = sys.argv[1:]

    if len(args) != 1:
        print('Usage: {} input.fa'.format(os.path.basename(sys.argv[0])))
        sys.exit(1)

    fasta = args[0]

    print('Processing "{}"'.format(fasta))
    check_e6(fasta)


# --------------------------------------------------
if __name__ == '__main__':
    main()
