"""
File to create .gb files of PaVE genomes to run VaPiD for PuMA vs VAPiD comparison

KVD Lab, University of Arizona

Author: Dr. Koenraad Van Doorslaer
"""



import csv
from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from Bio.Alphabet import IUPAC
from Bio.SeqFeature import SeqFeature, FeatureLocation

exclude=["E6*","E1^E4","E8^E2","URR","E1BS","E2BS"]

accessions=[]
for r in csv.reader(open('results.csv',"r")):
    if r[0] not in accessions:
        accessions.append(r[0])


with open('PaVE.gb',"w") as genbank:
    for a in accessions:
        print (a)
        for r in csv.reader(open('PaVE.csv',"r")):
            if r[0] == a and r[1] not in exclude and "join" not in r[2]:
                if r[1] == 'CG':
                    sequence_object = Seq(r[3],IUPAC.unambiguous_dna)
                    record = SeqRecord(sequence_object,
                       id=a, # random accession number
                       name=a,
                       description='An example GenBank file generated by BioPython')
                    
                else:
                    s,e = int(r[2].split("..")[0])-1,int(r[2].split("..")[1])
                    feature = SeqFeature(FeatureLocation(start=s, end=e), type='CDS', qualifiers={'gene':r[1]})
                    record.features.append(feature)
        print (record.format("gb"),file=genbank)
